### ISSUE TITLE
Compatibility with Drupal 9

### ISSUE THREAD

**Issue by dougzilla** [ubc-web-services/clf#22]
I installed Galacticus v1.0.3 on a Drupal 9.1.7 site, then tried to install CLF v1.0.3
CLF v1.0.3 shows as being incompatible with Drupal 9.

Added this line
'core_version_requirement: '^8 || ^9' to the 'themes/custom/clf-master/clf.info.yml' file.

Drupal does not seem to mind this, I can enable the CLF theme.

But, I cannot get the site to recognize the 'themes/custom/clf-master/css/unit.custom.css'.
It insists on using 'https://cdn.ubc.ca/clf/7.0.4-minimal/css/minimal-clf-full-7.0.4-bw.css'

So the question is, is the a Drupal 9 ready version of the CLF?

**Comment by dougzilla** [comment]
I modified 2 files in the CLF theme. It seems to work now in Drupal 9 and my install uses the 'custom/clf/css/unit.custom.css' file as it should.
Please see the text file to see the changes.
[clf-customization.txt](https://github.com/ubc-web-services/clf/files/6367660/clf-customization.txt)

**Comment by joelpittet** [comment]
Thanks @dougzilla, I've updated the core_version_requirement, and will see about the CSS aspect of things
